const EmojiBank = {
  level0: [
    { emoji: "❤️👰🏃", answers: ["Dilwale Dulhania Le Jayenge"] },
    { emoji: "👦🚲🏫", answers: ["3 Idiots"] },
    { emoji: "🕴️🕶️💰", answers: ["Don"] },
    { emoji: "👸💔🏰", answers: ["Jodhaa Akbar"] },
    { emoji: "🧊", answers: ["Barfi"] },
    { emoji: "🏏🇮🇳🔥", answers: ["Lagaan"] },
    { emoji: "🛳️💍💔", answers: ["Titanic"] },
    { emoji: "⭐🌍", answers: ["Taare Zameen Par"] },
    { emoji: "👮‍♂️💣🚂", answers: ["Baby"] },
    { emoji: "🦁👑🌍", answers: ["The Lion King"] },

    { emoji: "😡👨‍⚖️🔨", answers: ["Pink"] },
    { emoji: "👩‍❤️‍👨🎶🎤", answers: ["Aashiqui 2"] },
    { emoji: "🕷️🧑‍🦱🕸️", answers: ["Spider-Man"] },
    { emoji: "🎤⭐🇮🇳", answers: ["Rockstar"] },
    { emoji: "👨‍🍳🔥🍽️", answers: ["Chef"] },
    { emoji: "🧛‍♂️🌙🩸", answers: ["Twilight"] },
    { emoji: "👨‍🚀🌕🚀", answers: ["Interstellar"] },
    { emoji: "🤖👦💙", answers: ["Robot"] },
    { emoji: "🏹🔥👧", answers: ["The Hunger Games"] },
    { emoji: "🧞‍♂️💡👦", answers: ["Aladdin"] },

    { emoji: "👮‍♂️💼🔫", answers: ["Loot"] },
    { emoji: "💘👫🎒", answers: ["Kabaddi"] },
    { emoji: "🎶👦👧💔", answers: ["Prem Geet"] },
    { emoji: "🏔️🧗‍♂️🇳🇵", answers: ["Everest"] },
    { emoji: "🔥👨‍👩‍👦", answers: ["Jhola"] },
    { emoji: "🏥👩‍⚕️💔", answers: ["Classic"] },
    { emoji: "🎤👨‍🎤🇳🇵", answers: ["Kusume Rumal"] },
    { emoji: "🚌👬😂", answers: ["Chhakka Panja"] },
    { emoji: "👦🗡️🕊️", answers: ["Bir Bikram"] },
    { emoji: "👩‍❤️‍👨🌧️", answers: ["A Mero Hajur"] },
    { emoji: "🐅👨‍🌾🪓", answers: ["Kalo Pothi"] },
    { emoji: "👮‍♂️🚔💥", answers: ["Xira"] },
    { emoji: "🙏👨‍👩‍👦🇳🇵", answers: ["Bulbul"] },
    { emoji: "💃🎵❤️", answers: ["Nai Nabhannu La"] },
    { emoji: "🕊️👩‍👧💔", answers: ["Seto Sur"] },
  ],
};

export default EmojiBank;
